 
 
  WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','R','SR')),
  
  SETOR AS (SELECT ZOCODIGO,ZODESCRICAO FROM ZONA WHERE ZOCODIGO IN (20,21,22,23,24,25,26,27,28)),
  
  ENDE AS (SELECT ENDCODIGO,CLICODIGO,ZODESCRICAO FROM ENDCLI INNER JOIN SETOR ON ENDCLI.ZOCODIGO=SETOR.ZOCODIGO WHERE ENDFAT='S'),
  
  PEDBAIXA AS (SELECT PEDDTBAIXA,ID_PEDIDO,PEDID.CLICODIGO,ZODESCRICAO FROM PEDID INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
    INNER JOIN ENDE ON PEDID.CLICODIGO=ENDE.CLICODIGO AND PEDID.ENDCODIGO=ENDE.ENDCODIGO
     WHERE  (
    PEDDTBAIXA BETWEEN 
        CAST(EXTRACT(YEAR FROM CURRENT_DATE) || '-01-01' AS DATE) AND 
        DATEADD(DAY, -1, CAST(EXTRACT(YEAR FROM CURRENT_DATE) || '-12-31' AS DATE))
    OR 
    PEDDTBAIXA BETWEEN 
        DATEADD(YEAR, -1, CAST(EXTRACT(YEAR FROM CURRENT_DATE) || '-01-01' AS DATE)) AND 
        DATEADD(DAY, -1, CAST(EXTRACT(YEAR FROM CURRENT_DATE) || '-12-31' AS DATE))
) AND PEDSITPED<>'C' AND PEDLCFINANC IN ('S', 'L','N'))
  

 SELECT PEDDTBAIXA,CLICODIGO,ZODESCRICAO SETOR,SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA 
   FROM PDPRD 
    INNER JOIN PEDBAIXA ON PDPRD.ID_PEDIDO=PEDBAIXA.ID_PEDIDO
     GROUP BY 1,2,3