
  WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','R','SR')),
  
  SETOR AS (SELECT ZOCODIGO,ZODESCRICAO FROM ZONA WHERE ZOCODIGO IN (20,21,22,23,24,25,26,27,28)),
  
  ENDE AS (SELECT ENDCODIGO,CLICODIGO,ZODESCRICAO FROM ENDCLI INNER JOIN SETOR ON ENDCLI.ZOCODIGO=SETOR.ZOCODIGO WHERE ENDFAT='S'),
  
  PEDBAIXA AS (SELECT PEDDTBAIXA,ID_PEDIDO,PEDID.CLICODIGO,ZODESCRICAO FROM PEDID INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
    INNER JOIN ENDE ON PEDID.CLICODIGO=ENDE.CLICODIGO AND PEDID.ENDCODIGO=ENDE.ENDCODIGO
     WHERE PEDDTBAIXA BETWEEN
             DATEADD(MONTH, -11, CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 1) AND
                                 'YESTERDAY' OR  PEDDTBAIXA 
                                 BETWEEN DATEADD(MONTH, -11,DATEADD(YEAR, -1, CURRENT_DATE) - EXTRACT(DAY FROM CURRENT_DATE) + 1) AND DATEADD(YEAR, -1, CURRENT_DATE) AND PEDSITPED<>'C' AND PEDLCFINANC IN ('S', 'L','N')),
  
  PROD AS (SELECT PROCODIGO FROM PRODU WHERE PROTIPO IN ('E','P','F'))
  

 SELECT PEDDTBAIXA,PD.PROCODIGO,PDPDESCRICAO,CLICODIGO,ZODESCRICAO SETOR,SUM(PDPQTDADE)QTD 
   FROM PDPRD PD
    INNER JOIN PEDBAIXA ON PD.ID_PEDIDO=PEDBAIXA.ID_PEDIDO
     INNER JOIN PROD P ON PD.PROCODIGO=P.PROCODIGO
     
     GROUP BY 1,2,3,4,5